### ISSUE TITLE
Opening up settings page quickly corrupts view

### ISSUE THREAD

**Issue by SWvheerden** [tari-project/universe#356] opened 2024-09-09 11:01 UTC
If you open up the settings page while you the screen `setting up tari truth machine` is still showing, it looks like the entire display disappears. It just shows the block, but not height meter or anything like that.

**Comment by SWvheerden** [comment] 2024-09-09 13:58
<img width="1390" alt="Screenshot 2024-09-09 at 15 58 01" src="https://github.com/user-attachments/assets/3c5c6e20-c3c7-44a1-b5d1-5397b5b3cca7">

**Comment by mmrrnn** [comment] 2024-09-10 16:23
This one might be fixed along with #410

**Comment by SWvheerden** [comment] 2024-09-10 17:19
This issue is worse in 0.29
Tries again to download xmrig, crashes on that and exit the whole startup screen

**Comment by SWvheerden** [comment] 2024-09-10 17:23
<img width="1440" alt="Screenshot 2024-09-10 at 19 20 25" src="https://github.com/user-attachments/assets/bd2f3b3c-8735-4ce3-9932-c334ae8a13cb">
It failed xmrig download and got stuck here. Did not download node or wallet

**Comment by mmrrnn** [comment] 2024-09-10 19:11
Yeah, loks pretty bad. I'll try to reproduce it on mac tomorrow because I'm not able to broke it on linux

**Comment by SWvheerden** [comment] 2024-09-11 06:13
Everytime it breaks its when it tries to access the xmrig API: `https://api.xmrig.com/1/latest_release`
For some reason, any PC on my network fails to access that through universe but a web browser works fine. 
After that fails all of this weird stuff happens.

**Comment by mmrrnn** [comment] 2024-09-11 18:43
Should be fixed along with #357

**Comment by SWvheerden** [comment] 2024-09-12 15:15
Still preset on 0.3.2
<img width="1458" alt="Screenshot 2024-09-12 at 17 15 10" src="https://github.com/user-attachments/assets/54b7b2ed-4746-4e46-831b-35eb2f78ea98">

**Comment by mmrrnn** [comment] 2024-09-17 22:25
https://github.com/tari-project/universe/pull/493

Hope this will fixed the issue, I've sent binary with potential fix to [SW van Heerden] as i still can't reproduce it

**Comment by SWvheerden** [comment] 2024-09-18 09:59
Managed to reproduce it again on my win machine
steps:
open settings
disable CPU mining
disable GPU mining
close settings
click on start mining,

**Comment by SWvheerden** [comment] 2024-09-18 10:07
The issue is there, that mining button. 
That loop cannot handle exceptions and restart. If something goes wrong there it crashes and gets stuck

**Comment by mmrrnn** [comment] 2024-09-18 16:00
Yeah, handled that issue with both cpu and gpu mining disabled:
https://github.com/tari-project/universe/pull/493/commits/c29953ea08a95aab13f588d49015e30c1b16486d

**Comment by SWvheerden** [comment] 2024-09-18 16:53
Thats not in the build you gave me to test right?
But check the loop that starts mining, make sure it can exit all all error cases and resets properly

**Comment by mmrrnn** [comment] 2024-09-19 08:05
All setup checks I made here: https://github.com/tari-project/universe/pull/443

it's another not merged PR

**Comment by SWvheerden** [comment] 2024-09-19 11:55
<img width="1405" alt="Screenshot 2024-09-19 at 13 54 49" src="https://github.com/user-attachments/assets/9e5105a8-cf15-4bb7-9810-3401a4dda6a8">
I would like to test that. 
Because here I am trying to start mining. Something went wrong. Dont know what. Adn its now completely frozen and dead

**Closed** 2024-09-24 08:24 UTC
