### ISSUE TITLE
0.1.37 crashes on M3 when start mining and shows a corrupted app icon

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#127] opened 2024-08-23 19:01 UTC
**Describe the bug**
I went through the auto update, go tthe message that says "ready to restart" clicked OK, and now when I run it it immediately crashes

Naveen's task bar:

![image](https://github.com/user-attachments/assets/e443a5af-cc86-4918-b4df-a17be55034ce)

**Comment by stringhandler** [comment] 2024-08-26 09:01
I think this is caused by the autoupdate. We probably won't update the icon in future, so maybe not that serious?

**Comment by brianp** [comment] 2024-11-14 10:38
Version listed is old. Issue may or may not be resolved. Auto-update enhancements are in the pipeline anyway. Closing for now.

**Closed by brianp** 2024-11-14 10:38 UTC
