### ISSUE TITLE
v0.2.7 GPU mining logs need to be added to logs

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#373] opened 2024-09-09 18:31 UTC
Describe the bug
GPU mining logs need to be added to logs

<img width="317" alt="Screenshot 2024-09-09 at 2 23 40 PM" src="https://github.com/user-attachments/assets/4dd342bf-6e2d-464e-9637-c6f90bb45a5b">

**Comment by stringhandler** [comment] 2024-09-09 18:34
duplicate of #270

**Closed** 2024-09-10 08:25 UTC
