### ISSUE TITLE
Don't let me install TU on a machine/OS that is too old

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#123] opened 2024-08-23 14:45 UTC
**Describe the bug**
E.g. Big Sur might be too old because the webGL animations don't render on my machine (although they do on Lusion's demo).

**Comment by stringhandler** [comment] 2024-08-27 13:49
Need more info: What is too old?

**Comment by mmrrnn** [comment] 2024-11-14 08:14
Duplicate of [#193](https://github.com/tari-project/universe/issues/193)?

**Comment by brianp** [comment] 2024-11-14 10:38
Closing as won't fix. Maybe resolved with #193 maybe not. It'll resurface if it's an issue.

**Closed by brianp** 2024-11-14 10:38 UTC
