### ISSUE TITLE
0.2.3 : GetSyncProgress not made available 

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#301] opened 2024-09-04 20:28 UTC
**Describe the bug**
"GetSyncProgress not made available" error toast on Windows, build 0.2.3

Animation proceeds, but nothing is mining.

**Comment by stringhandler** [comment] 2024-09-05 07:43
This must be caused by a previous version of the base node. When it upgrades to 1.4.0-pre.0, it should be resolved. We are busy with another fix which will specify the minimum version of the base node needed, which will force the upgrade, but will keep it open until then.

should be fixed by #244

**Closed** 2024-09-11 14:46 UTC
