### ISSUE TITLE
Beta build stopped mining and then I received the ffg error

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#879] opened 2024-10-17 14:10 UTC
**Describe the bug**
After a while, the Beta build stopped mining and then I received the ffg error. The miner has been running for >1 hour and when checked, no blocks appeared, when I clicked into the universe app, I received error attached.

**To Reproduce**
1. Tari Universe should be open and running
2. After about an hour the miner just stopped mining and gave me the ffg error.

**Expected behavior**
Miner should run without any failures and errors.

**Screenshots**
![Screenshot (150)](https://github.com/user-attachments/assets/92df50e2-0e4c-4989-aca9-7c534bd2abf5)

**Desktop (please complete the following information):**
 - Windows & Version: Windows 11,version 23H2, Intel core i7 
 - Browser & Version Tari Universe Beta v0.5.26

**Log file:**
[esmeralda.zip](https://github.com/user-attachments/files/17413772/esmeralda.zip)

**Comment by brianp** [comment] 2024-11-14 14:57
Looks like maybe a chain split occurred. Something to watch out for but steps not reproducible. Closing for now.

**Closed by brianp** 2024-11-14 14:57 UTC
