### ISSUE TITLE
Macos - When tari universe awakes from sleep, the telemetry service doesn't post anything

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#711] opened 2024-10-03 09:40 UTC
To reproduce:
* Run a macos m3 or similar
* Run tari universe.
* Look at the universe log. Take note that there is a telemetry log every minute. "Telemetry data sent"
* Let the machine go to sleep for about 10 minutes
* Wake the machine up

Expected:
* in logs, "Telemetry data sent" is sent again every minute

Actual:
No telemetry is sent.

This could be related to a frontend thread making a call to status or somethign that is holding a lock and not allowing the telemetry to continue

**Comment by MCozhusheck** [comment] 2024-10-08 07:49
Couldn't reproduce on intel and M1 mac.
The issue could be temporary caused by disconnected internet - in my trials tari universe V1 temporary stopped sending telemetry data but I started again after some time (around 2 minutes)

**Comment by brianp** [comment] 2024-11-14 11:37
Closing as can't reproduce until reproducable, or spotted again.

**Closed by brianp** 2024-11-14 11:37 UTC
