### ISSUE TITLE
0.3.1 GPU at billions of hashes, only one GPU shown

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#447] opened 2024-09-11 22:25 UTC
**Describe the bug**

https://t.me/OrderOfSoon/671
![telegram-cloud-photo-size-1-5120793192835427591-m](https://github.com/user-attachments/assets/9e04b8bb-a52d-4187-84c5-fdcd48effd07)
![telegram-cloud-photo-size-1-5120793192835427588-x](https://github.com/user-attachments/assets/1a0fb180-d68f-4d04-831e-eb0d41573870)

**Comment by stringhandler** [comment] 2024-09-13 07:49
These two must be added together in the gpu miner

**Comment by stringhandler** [comment] 2024-09-16 07:31
Duplicate of #461

**Comment by stringhandler** [comment] 2024-09-16 07:31
Closing in favour of other one

**Closed by stringhandler** 2024-09-16 07:31 UTC
