### ISSUE TITLE
v.0.40 Cannot complete initial sync on Windows VM

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#208] opened 2024-08-28 13:53 UTC
**Describe the bug**
When opening the Tari Universe application on a Windows VM, the intial sync gets stuck at 13% and will not progress further. 
Tested on v0.1.40 most recently but have had troubles with previous versions as well. 

Logs:
[universe (1).zip](https://github.com/user-attachments/files/16784303/universe.1.zip)

**Screenshots**
![Screenshot 2024-08-28 at 9 50 59 AM](https://github.com/user-attachments/assets/353ef729-9f71-480d-b5ea-57a8bed2cdb3)

![Screenshot 2024-08-28 at 9 51 28 AM](https://github.com/user-attachments/assets/a5446d83-b10e-4879-bc1d-5cdadd39b588)

![Screenshot 2024-08-28 at 10 05 55 AM](https://github.com/user-attachments/assets/a11d3f80-7bfb-44b1-8d98-cf993ce2a989)

![Screenshot 2024-08-28 at 10 06 49 AM](https://github.com/user-attachments/assets/ed5906ff-75c7-46aa-8f78-004c22ff4aaa)

**Desktop (please complete the following information):**
 - OS & Version: Windows VM 
![Screenshot 2024-08-28 at 9 53 24 AM](https://github.com/user-attachments/assets/1664cfb0-5576-4a13-957e-457a8c5e4412)

**Comment by mmrrnn** [comment] 2024-09-02 15:36
This might be caused by veeeery slow syncing process. Today I was testing my pr where syncing progress is displayed on the UI and for a while i had 0blocks/sec:


![Image](https://github.com/user-attachments/assets/03237ec0-3941-48d6-805d-3aba6089f6af)

**Comment by stringhandler** [comment] 2024-09-06 08:06
Not sure if this is still an issue. Closing due to age

**Closed by stringhandler** 2024-09-06 08:06 UTC
