### ISSUE TITLE
Miner screen looses all text content when the user clicks on Mining settings

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1040] opened 2024-11-07 12:24 UTC
**Describe the bug**
After the user clicks on Mining setting they get redirected back to the miner but all the text content is missing. Only the blocks shows on the miner screen.

**To Reproduce**
1. Go to settings
2. Click on Mining settings
3. User gets redirected back to the miner
4. Only the blocks shows up on the miner, all text content no longer shows

**Expected behavior**
User should be able to change their mining settings

**Screenshots**
<img width="1382" alt="image" src="https://github.com/user-attachments/assets/bb3cb4f4-6bd9-4789-8764-5a39d8241632">

**Desktop (please complete the following information):**
 - OS & Version: Macbook Air 13 inch M1 2020 Sequoia v15.1
 - Browser & Version Testnet v0.6.0

**Comment by Tas4tari** [comment] 2024-11-07 19:39
Duplicate of: https://github.com/tari-project/universe/issues/1035

**Closed** 2024-11-14 12:40 UTC
